spring:
  redis:
    host: localhost
    port: 6379

  application:
    name: zipin

  datasource:
    url: jdbc:mysql://localhost:3306/db_zipin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 或 create、create-drop、validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: info
    io.github.han9912.zipin: debug
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: "this-is-a-strong-secret-key-with-32+-bytes"