spring:
  redis:
    host: localhost
    port: 6379

  data:
    redis:
      repositories:
        enabled: false

  application:
    name: zipin

  datasource:
    url: jdbc:mysql://localhost:3306/db_zipin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: info
    io.github.han9912.zipin: debug
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: "this-is-a-strong-secret-key-with-32+-bytes"

redisson:
  address: redis://127.0.0.1:6379

mybatis:
  mapper-locations: classpath:mappers/*.xml